// <auto-generated />
using FlowChartApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowChartApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204165607_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("FlowChartApp.Models.FlowBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorderStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionArabic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkLeftText")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkLeftUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkMiddleText")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkMiddleUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkRightText")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkRightUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL");

                    b.Property<string>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FlowBoxes");
                });

            modelBuilder.Entity("FlowChartApp.Models.FlowConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelIcon")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceBoxId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetBoxId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Waypoints")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceBoxId");

                    b.HasIndex("TargetBoxId");

                    b.ToTable("FlowConnections");
                });

            modelBuilder.Entity("FlowChartApp.Models.LegendItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorderStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LegendItems");
                });

            modelBuilder.Entity("FlowChartApp.Models.FlowConnection", b =>
                {
                    b.HasOne("FlowChartApp.Models.FlowBox", "SourceBox")
                        .WithMany("OutgoingConnections")
                        .HasForeignKey("SourceBoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowChartApp.Models.FlowBox", "TargetBox")
                        .WithMany()
                        .HasForeignKey("TargetBoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceBox");

                    b.Navigation("TargetBox");
                });

            modelBuilder.Entity("FlowChartApp.Models.FlowBox", b =>
                {
                    b.Navigation("OutgoingConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
